image: gradle:alpine


stages:          
  - build
  - test
  - deploy

build:
    stage: build
    image: adoptopenjdk/openjdk11
    script:
        - chmod +x gradlew 
        - ./gradlew clean build
    artifacts:
        paths:
            - build/libs/*.jar

# test: 
#     stage: test
#     script:
#         - chmod +x gradlew  
#         - ./gradlew test

        
deploy to s3:
    stage: deploy
    image: 
        name: amazon/aws-cli
        entrypoint: [""]
    dependencies:
        - build
    script:
        - aws --version
        - aws s3 rm s3://$S3_BUCKET --recursive
        - aws s3 cp public s3://$S3_BUCKET --recursive
