image: adoptopenjdk/openjdk11

stages:          
  - build
  - test
  - deploy

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

build:
    stage: build
    script:
        - chmod +x gradlew 
        - ./gradlew clean build
    artifacts:
        paths:
            - build/libs/*.jar
    only:
        - main

test: 
    stage: test
    script:
        - chmod +x gradlew  
        - ./gradlew test