image: gradle:alpine


stages:          
  - build
  - test
  - deploy

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

build:
    stage: build
    image: adoptopenjdk/openjdk11
    script:
        - chmod +x gradlew 
        - ./gradlew clean build
    artifacts:
        paths:
            - build/libs/*.jar
