image: gradle:alpine


stages:          
  - build
  - test
  - deploy

build:
    stage: build
    image: adoptopenjdk/openjdk11
    script:
        - chmod +x gradlew 
        - ./gradlew clean build
    artifacts:
        paths:
            - build/libs/*.jar

test: 
    stage: test
    script:
        - chmod +x gradlew  
        - ./gradlew test
