stages:
    - build
    - test

build:
    image: adoptopenjdk/openjdk11
    stage: build
    script:
        - ./gradlew clean
        - ./gradlew build
    artifacts:
        paths:
            - build/libs/*.jar

test:
    image: adoptopenjdk/openjdk11
    stage: test
    scripts:
        - ./gradlew test


 
