image: gradle:alpine
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
before_script:
   - chmod +x gradlew
   - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
 paths:
   - .gradle/wrapper
   - .gradle/caches
   - build/


stages:
  - build
  - develop


job-build:
  stage: build
  only:
  - master
  script:
  - ./gradlew clean
  - ./gradlew build

job-develop:
  stage: develop
  only:
  - spring-api-dev
  script:
  - ./gradlew clean
  - ./gradlew build


